on:
  push:
    branches: main
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened]
    branches: main

name: 🤖 Release

jobs:
  zip:
    name: 📦 Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean files
        run: |
          mkdir -p package/sharpestaddon
          mv addons package/sharpestaddon
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SharpestAddon
          path: package
